---

################# Palo Deploy New Objects ################
##
## Requirements: Ansible 2.9+ & PanOS Ansible Collection
## Written by: Daniel Bostock
## Contact: contact@danielbostock.com
## Version: 1.0
## License: MIT
## 


- name: Add some service objects to the firewall
  hosts: localhost
  connection: local
  gather_facts: False

## Ensure the Palo Alto Ansible Role (Collection) has been installed. There are some requirements as well for the
## role. Often you will get prompted if you need a specific module such as for example paramiko.
## Review documentation here - https://github.com/PaloAltoNetworks/pan-os-ansible

  collections:
    - paloaltonetworks.panos

## This is the vars file which is used to create the service objects. Add the objects into here that you
## would like to deploy.
  vars_files:
    - vars/service_objects.yml

## This variable is referenced with the commit action at the end of the play.

  vars:
    - panos_provider: 
        ip_address: '{{ fw_ip_address }}'
        username: '{{ fw_username }}'
        password: '{{ fw_password }}'
        api_key: '{{ api_key }}'
    - service_objects: ./service_objects.yml

## This admin list is used by the commit action at the end to commit any changes by specific users,
## with this playbook, it will be leveraging fvwadmin1 user only, adjust accordingly.
## Any other commits currently sitting in the Palo's will not be committed if they are under another user.

    - admins:
       - fwadmin1

  tasks:
## This task will grab the credentials stored in a vault file. I strongly suggest encrypting your credential
## variable file used here. Alternatively, remove the variables below that much panos_provider. You can
## if testing, manually insert the information instead of using a variable file.  
  - name: Grab the credentials from ansible-vault
    include_vars: 'vars/vaultfile.yml'
    no_log: 'yes'

## The tag parameter has been commented out, this is because the tag has to exist prior to this play
## being executed. Refer to my create_tag_object play and use the play actions in here along side this
## service object play actions. It is important to note the tag set of play actions is required before
## this play.

  - name: Create service objects
    panos_service_object:
      provider: '{{ panos_provider }}'
      name: '{{ item.value.service_name }}'
      destination_port: '{{ item.value.service_port }}'
      description: '{{ item.value.service_description }}'
      protocol: '{{ item.value.service_protocol }}'
      state: 'present'
      #tag: ['AnsibleTest']
    with_dict: "{{ service_objects }}"

## This will commit these changes 

  post_tasks:

  - name: Commit pending Panorama changes for specified admin list
    panos_commit:
      provider: "{{ panos_provider }}"
      admins: "{{ admins }}"